In [10]:
import io
import ipywidgets as widgets
import math
import numpy
import psycopg
import pandas as pd
import requests
import sqlite3
import sys
import tqdm
import warnings

from statsmodels.stats.multitest import fdrcorrection as fdr
from test_backend_config import load_config
from ipyfilechooser import FileChooser
from scipy import stats
from scipy.stats import ttest_ind
from sqlalchemy import create_engine
from sqlalchemy.dialects.postgresql import insert
from sqlite3 import Error
from sqlite3 import IntegrityError

In [ ]:
test_table = pd.DataFrame({
    'id': [1, 2, 3],
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35]
})
test_table

In [ ]:
# Loads database config values from database.ini file and validates that user and password are set.
config = load_config()
if (config['user'] == "" or config['password'] == ""):
    print("Please set your user and password in the database.ini file.")
    sys.exit(1)
    
# Creates a connection pool to PostgreSQL database using SQLAlchemy.
engine = create_engine(f"postgresql+psycopg://{config['user']}:{config['password']}@{config['host']}:{config['port']}/{config['database']}")

# Function to insert data into PostgreSQL table, skipping duplicates based on primary keys.
def postgres_skip_on_duplicate(pd_table, conn, keys, data_iter):
    data = [dict(zip(keys,row)) for row in data_iter]
    conn.execute(insert(pd_table.table).on_conflict_do_nothing(), data)


# Complete tap response data
print("working on tap_output:") 
test_table.to_sql('test_table', engine, if_exists='replace', index=False, method=None)
print("Done")

In [ ]:
def read(table, connection):
    """
    Fetches all rows from a specified table in a PostgreSQL database.
    
    Inputs:
        table (str): table name in PostgreSQL database
        connection (psycopg.Connection): Active psycopg database connection
    
    Returns:  
        pd.DataFrame: Table data as a DataFrame
    """
    with connection.cursor() as cursor:
        cursor.execute(f'SELECT * from "{table}"')

        # Fetch all rows from database
        record = cursor.fetchall()
        column_names = [desc[0] for desc in cursor.description]

    return pd.DataFrame(data=record, columns=column_names)

In [ ]:
with psycopg.connect(
    dbname=config['database'], 
    user=config['user'], 
    password=config['password'], 
    host=config['host'],
    port=config['port']
    ) as connection:
    Gene_Allele_WormbaseID = read("Gene_Allele_WormbaseID", connection)
    print(Gene_Allele_WormbaseID.head())

    return(Gene_Allele_WormbaseID)

In [8]:
from ast import literal_eval

t = '(0.0,1.0)'
print(t)
print(type(t))
print(literal_eval(t) if isinstance(t, str) else t)
print(type(literal_eval(t) if isinstance(t, str) else t))

(0.0,1.0)
<class 'str'>
(0.0, 1.0)
<class 'tuple'>

In [18]:
d = {"Screen": ["One", "Two", "Three", "Four", "Three"], "dataset": ["StrainOne", "StrainTwo", "StrainThree", "StrainFour", "StrainOne"], "Morphwidth": [0, -66, -10, -20, 5], "Midline": [0, -240, -30, -600, 10]}
df = pd.DataFrame(data=d)
df

  Screen      dataset  Morphwidth  Midline
0    One    StrainOne           0        0
1    Two    StrainTwo         -66     -240
2  Three  StrainThree         -10      -30
3   Four   StrainFour         -20     -600
4  Three    StrainOne           5       10

In [13]:
def aggregate_unique_values(df, by):
    """
    Aggregates by specified keys and computes mean of numerical columns. 
    Transforms tstat_gene_data, tstat_allele_data , gene_profile_data, 
    and allele_profile_data tables
    
    Inputs:
        df (pd.DataFrame): Input DataFrame containing data to aggregate.
        by (list of str): Columns to group by
    
    Returns:
        grouped (pd.DataFrame): Aggregated dataframe with mean values and 
                                grouped 'Screen' list
    """
    if len(by) > 1 and 'Metric' in df.columns:
        df['Metric'] = pd.Categorical(df['Metric'], categories=df['Metric'].unique(), ordered=True)

    # Perform groupby aggregation
    grouped = df.groupby(by).agg(
        {col: 'mean' for col in df.columns if col not in by + ['Screen']}
    ).reset_index()

    # Aggregate the Screen column into a list
    grouped['Screen'] = df.groupby(by)['Screen'].apply(lambda x: list(set(x))).reset_index(drop=True)

    return grouped

In [19]:
a = aggregate_unique_values(df, ["dataset"]).explode('Screen').reset_index(drop=True)

In [20]:
a

       dataset  Morphwidth  Midline Screen
0   StrainFour       -20.0   -600.0   Four
1    StrainOne         2.5      5.0    One
2    StrainOne         2.5      5.0  Three
3  StrainThree       -10.0    -30.0  Three
4    StrainTwo       -66.0   -240.0    Two